name: badstrings
on: [pull_request, push]
jobs:
  badstrings:
    runs-on: ubuntu-latest
    steps:
      - name: scanning commit message for bad strings
        run: |
          #!/bin/bash
          set -euo pipefail
          IFS=$'\n\t'
          message="${{ github.event.head_commit.message }}"
          
          strings=($(curl -s https://raw.githubusercontent.com/someara/badstrings/main/strings.txt))
          for i in ${strings[@]} ; do
            echo "${message}" | grep -v "$i" &>/dev/null;
          done
